### Install the libraries

Questions
Answer the questions below to complete your homework.

1. Pandas version (1 point)

In [1]:
import sys
print(sys.version)

3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

Import the libraries

In [2]:
import numpy as np
import pandas as pd

Load the data

In [3]:
df =  pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

2. Records count (1 point)

In [5]:
df.shape

(10000, 11)

3. Fuel types (1 point)

In [6]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

4. Missing values (1 point)

In [7]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

5. Max fuel efficiency (1 point)

In [8]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [9]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

6. Median value of horsepower (1 point)

In [10]:
df.horsepower.median()

np.float64(254.0)

In [11]:
df.horsepower.isna().sum()

np.int64(877)

In [12]:
df["horsepower"] = df["horsepower"].fillna(df["horsepower"].mean())

In [13]:
df.horsepower.median()

np.float64(254.44601556505535)

7. Sum of weights (1 point)

In [14]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [15]:
df_asia = df[df['origin']== 'Asia']

In [16]:
df_asia.reset_index(drop=True, inplace=True)

In [17]:
df_asia = df_asia[['vehicle_weight','model_year']]

In [18]:
x = df_asia.head(7)

In [19]:
x

   vehicle_weight  model_year
0            4240        1996
1            4310        1992
2            4230        1997
3            4420        1978
4            3950        2007
5            4750        2021
6            4450        2019

In [20]:
XTX = x.T.dot(x)

In [21]:
XTX = x.T @ x

In [22]:
XTX

                vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424

In [23]:
invert_XTX =np.linalg.inv(XTX)

In [24]:
y =[1100, 1300, 800, 900, 1000, 1100, 1200]

In [25]:
w = invert_XTX@x.T@y

In [26]:
w.sum()

np.float64(0.369196969049255)